# Generated by Django 5.0.6 on 2024-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uongozini', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru')], default='Nairobi', max_length=100),
        ),
    ]
