# Generated by Django 5.1.3 on 2024-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uongozini', '0007_post_slug_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
